uvmf:
  environments:
    execute:
      agents:
      - initiator_responder: INITIATOR
        name: execute_in_agent
        type: execute_in
      - initiator_responder: RESPONDER
        name: execute_out_agent
        type: execute_out
      analysis_components:
      - name: predictor
        parameters: []
        type: exe_predictor
      analysis_exports: []
      analysis_ports: []
      config_constraints: []
      config_vars: []
      existing_library_component: 'True'
      hvl_pkg_parameters: []
      imports:
      - name: lc3_prediction_pkg
      non_uvmf_components: []
      parameters: []
      qvip_memory_agents: []
      scoreboards:
      - name: execute_scoreboard
        sb_type: uvmf_in_order_scoreboard
        trans_type: execute_out_transaction
      subenvs: []
      tlm_connections:
      - driver: predictor.execute_out_analysis_port
        receiver: execute_scoreboard.expected_analysis_export
        validate: 'True'
      - driver: execute_in_agent.monitored_ap
        receiver: predictor.execute_in_analysis_export
        validate: 'True'
      - driver: execute_out_agent.monitored_ap
        receiver: execute_scoreboard.actual_analysis_export
        validate: 'True'
