uvmf:
  environments:
    lc3:
      agents:
      - initiator_responder: INITIATOR
        name: imemResp
        type: imem
      - initiator_responder: INITIATOR
        name: dmemResp
        type: dmem
      analysis_components: []
      analysis_exports: []
      analysis_ports: []
      config_constraints: []
      config_vars: []
      existing_library_component: 'True'
      hvl_pkg_parameters: []
      imports:
      - name: fetch_env_pkg
      - name: decode_env_pkg
      - name: writeback_env_pkg
      - name: memaccess_env_pkg
      - name: control_env_pkg
      - name: execute_env_pkg
      non_uvmf_components: []
      parameters: []
      qvip_memory_agents: []
      scoreboards: []
      subenvs:
      - name: fetchEnv
        parameters: []
        reg_block_instance_name: fetchEnv_rm
        type: fetch
      - name: decodeEnv
        parameters: []
        reg_block_instance_name: decodeEnv_rm
        type: decode
      - name: writebackEnv
        parameters: []
        reg_block_instance_name: writebackEnv_rm
        type: writeback
      - name: memaccessEnv
        parameters: []
        reg_block_instance_name: memaccessEnv_rm
        type: memaccess
      - name: controlEnv
        parameters: []
        reg_block_instance_name: controlEnv_rm
        type: control
      - name: executeEnv
        parameters: []
        reg_block_instance_name: executeEnv_rm
        type: execute
      tlm_connections: []
